---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
spec:
  containers:
    - name: javawebappcontainer
      image: ashokit/javawebapp
      ports:
        - containerPost: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: ClusterIP / NodePort / LoadBalancer
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30785
...

# note:- ClusterIP is used within the cluster for communication between Pods (as pod can die and get a new ip so we can get a static ip for all pods)
# note:- While using LoadBalancer dont use nodePort.
