---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: javawebappdp
  namespace: dev
spec:
  replicas: 3
  selector:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: ashokit/javawebapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: javawebappsvc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30785
...
